- id: gofumpt
  name: gofumpt
  description: Run gofumpt
  entry: gofumpt -w
  types: [go]
  language: golang
  pass_filenames: True
  additional_dependencies: ["mvdan.cc/gofumpt"]
- id: gci
  name: gci
  description: Control golang package import order and make it always deterministic.
  entry: gci write
  types: [go]
  language: golang
  pass_filenames: True
  additional_dependencies: ["github.com/daixiang0/gci"]
- id: go-mod-tidy
  name: Run go mod tidy
  entry: ./go-mod-tidy
  files: '\.go$|go.mod$|go.sum$'
  language: script
  args: ["."]
  pass_filenames: false
